[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
boto3 = "^1.34.134"
awslambdaric = "^2.0.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
